### ISSUE TITLE
error: cannot initialize a parameter of type 'simBool *' (aka 'unsigned char *') with an lvalue of type 'bool *'

### ISSUE THREAD

**Issue by 8krisv** [CoppeliaRobotics/simExtROS2Interface#16] opened 2023-01-28 19:15 UTC
I'm getting the following error when i'm trying to compile the plugin in ubuntu 22.04:

```
Starting >>> sim_ros2_interface
[Processing: sim_ros2_interface]                             
[Processing: sim_ros2_interface]ros2_interface:build 90% - 1min 0.2s]
[Processing: sim_ros2_interface]                                       
[Processing: sim_ros2_interface]                                       
[Processing: sim_ros2_interface]                                       
--- stderr: sim_ros2_interface                                         
/home/krisv/Documentos/CoppeliaSim_Edu_V4_4_0_rev0_Ubuntu22_04/programming/libPlugin/simPlusPlus/Lib.cpp:281:49: error: cannot initialize a parameter of type 'simBool *' (aka 'unsigned char *') with an lvalue of type 'bool *'
    int ret = simGetStackBoolValue(stackHandle, boolValue);
                                                ^~~~~~~~~
/home/krisv/Documentos/CoppeliaSim_Edu_V4_4_0_rev0_Ubuntu22_04/programming/libPlugin/simPlusPlus/Lib.cpp:584:36: error: cannot initialize a parameter of type 'simFloat *' (aka 'float *') with an rvalue of type 'double *'
    if(simGetFloatParam(parameter, &ret) == -1)
                                   ^~~~
/home/krisv/Documentos/CoppeliaSim_Edu_V4_4_0_rev0_Ubuntu22_04/programming/libPlugin/simPlusPlus/Lib.cpp:646:58: error: cannot initialize a parameter of type 'simFloat *' (aka 'float *') with an rvalue of type 'double *'
    if(simGetObjectFloatParam(objectHandle, parameterID, &ret) == -1)
                                                         ^~~~
/home/krisv/Documentos/CoppeliaSim_Edu_V4_4_0_rev0_Ubuntu22_04/programming/libPlugin/simPlusPlus/Lib.cpp:773:25: error: cannot initialize a parameter of type 'const simChar *' (aka 'const char *') with an lvalue of type 'void *'
    if(simReleaseBuffer(buffer) == -1)
                        ^~~~~~
/home/krisv/Documentos/CoppeliaSim_Edu_V4_4_0_rev0_Ubuntu22_04/programming/libPlugin/simPlusPlus/Lib.cpp:814:65: error: cannot initialize a parameter of type 'simFloat *' (aka 'float *') with an rvalue of type 'std::array<double, 12>::pointer' (aka 'double *')
    if(simGetObjectMatrix(objectHandle, relativeToObjectHandle, ret.data()) == -1)
                                                                ^~~~~~~~~~
/home/krisv/Documentos/CoppeliaSim_Edu_V4_4_0_rev0_Ubuntu22_04/programming/libPlugin/simPlusPlus/Lib.cpp:821:65: error: cannot initialize a parameter of type 'const simFloat *' (aka 'const float *') with an rvalue of type 'std::array<double, 12>::const_pointer' (aka 'const double *')
    if(simSetObjectMatrix(objectHandle, relativeToObjectHandle, matrix.data()) == -1)
                                                                ^~~~~~~~~~~~~
/home/krisv/Documentos/CoppeliaSim_Edu_V4_4_0_rev0_Ubuntu22_04/programming/libPlugin/simPlusPlus/Lib.cpp:846:70: error: cannot initialize a parameter of type 'simFloat *' (aka 'float *') with an rvalue of type 'std::array<double, 3>::pointer' (aka 'double *')
    if(simGetObjectOrientation(objectHandle, relativeToObjectHandle, ret.data()) == -1)
                                                                     ^~~~~~~~~~
/home/krisv/Documentos/CoppeliaSim_Edu_V4_4_0_rev0_Ubuntu22_04/programming/libPlugin/simPlusPlus/Lib.cpp:853:70: error: cannot initialize a parameter of type 'const simFloat *' (aka 'const float *') with an rvalue of type 'std::array<double, 3>::const_pointer' (aka 'const double *')
    if(simSetObjectOrientation(objectHandle, relativeToObjectHandle, eulerAngles.data()) == -1)
                                                                     ^~~~~~~~~~~~~~~~~~
/home/krisv/Documentos/CoppeliaSim_Edu_V4_4_0_rev0_Ubuntu22_04/programming/libPlugin/simPlusPlus/Lib.cpp:874:67: error: cannot initialize a parameter of type 'simFloat *' (aka 'float *') with an rvalue of type 'std::array<double, 3>::pointer' (aka 'double *')
    if(simGetObjectPosition(objectHandle, relativeToObjectHandle, ret.data()) == -1)
                                                                  ^~~~~~~~~~
/home/krisv/Documentos/CoppeliaSim_Edu_V4_4_0_rev0_Ubuntu22_04/programming/libPlugin/simPlusPlus/Lib.cpp:881:67: error: cannot initialize a parameter of type 'const simFloat *' (aka 'const float *') with an rvalue of type 'std::array<double, 3>::const_pointer' (aka 'const double *')
    if(simSetObjectPosition(objectHandle, relativeToObjectHandle, position.data()) == -1)
                                                                  ^~~~~~~~~~~~~~~
/home/krisv/Documentos/CoppeliaSim_Edu_V4_4_0_rev0_Ubuntu22_04/programming/libPlugin/simPlusPlus/Lib.cpp:888:69: error: cannot initialize a parameter of type 'simFloat *' (aka 'float *') with an rvalue of type 'std::array<double, 4>::pointer' (aka 'double *')
    if(simGetObjectQuaternion(objectHandle, relativeToObjectHandle, ret.data()) == -1)
                                                                    ^~~~~~~~~~
/home/krisv/Documentos/CoppeliaSim_Edu_V4_4_0_rev0_Ubuntu22_04/programming/libPlugin/simPlusPlus/Lib.cpp:895:69: error: cannot initialize a parameter of type 'const simFloat *' (aka 'const float *') with an rvalue of type 'std::array<double, 4>::const_pointer' (aka 'const double *')
    if(simSetObjectQuaternion(objectHandle, relativeToObjectHandle, quaternion.data()) == -1)
                                                                    ^~~~~~~~~~~~~~~~~
/home/krisv/Documentos/CoppeliaSim_Edu_V4_4_0_rev0_Ubuntu22_04/programming/libPlugin/simPlusPlus/Lib.cpp:918:43: error: cannot initialize a parameter of type 'simFloat *' (aka 'float *') with an rvalue of type 'std::array<double, 3>::pointer' (aka 'double *')
    if(simGetObjectVelocity(objectHandle, lin.data(), ang.data()) == -1)
                                          ^~~~~~~~~~
/home/krisv/Documentos/CoppeliaSim_Edu_V4_4_0_rev0_Ubuntu22_04/programming/libPlugin/simPlusPlus/Lib.cpp:952:22: error: cannot initialize a parameter of type 'const simChar *' (aka 'const char *') with an lvalue of type 'int *'
    simReleaseBuffer(returnedBuff);
                     ^~~~~~~~~~~~
14 errors generated.
gmake[2]: *** [CMakeFiles/simExtROS2.dir/build.make:157: CMakeFiles/simExtROS2.dir/home/krisv/Documentos/CoppeliaSim_Edu_V4_4_0_rev0_Ubuntu22_04/programming/libPlugin/simPlusPlus/Lib.cpp.o] Error 1
gmake[2]: *** Se espera a que terminen otras tareas....
/home/krisv/Documentos/rob2023/ros2_coppe/src/sim_ros2_interface/src/sim_ros2_interface.cpp:787:27: warning: object backing the pointer will be destroyed at the end of the full-expression [-Wdangling-gsl]
            auto &param = params_client->get_parameters({in->name}).front();
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/krisv/Documentos/rob2023/ros2_coppe/src/sim_ros2_interface/src/sim_ros2_interface.cpp:798:27: warning: object backing the pointer will be destroyed at the end of the full-expression [-Wdangling-gsl]
            auto &param = params_client->get_parameters({in->name}).front();
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/krisv/Documentos/rob2023/ros2_coppe/src/sim_ros2_interface/src/sim_ros2_interface.cpp:809:27: warning: object backing the pointer will be destroyed at the end of the full-expression [-Wdangling-gsl]
            auto &param = params_client->get_parameters({in->name}).front();
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/krisv/Documentos/rob2023/ros2_coppe/src/sim_ros2_interface/src/sim_ros2_interface.cpp:820:27: warning: object backing the pointer will be destroyed at the end of the full-expression [-Wdangling-gsl]
            auto &param = params_client->get_parameters({in->name}).front();
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 warnings generated.
gmake[1]: *** [CMakeFiles/Makefile2:164: CMakeFiles/simExtROS2.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< sim_ros2_interface [2min 31s, exited with code 2]

Summary: 0 packages finished [2min 31s]
  1 package failed: sim_ros2_interface
  1 package had stderr output: sim_ros2_interface

```

**Comment by fferri** [comment] 2023-01-30 11:42
Duplicate of #13

**Closed as completed by fferri** 2023-01-30 11:42 UTC
